---
tasks:
  - name: install haproxy
    yum: 
      name: haproxy
      state: started
      enabled: on
  
  - name: copy haproxy template file
    template:
       src: haproxy.conf.j2
       dest: /etc/haproxy/haproxy.conf
    notify: restart haproxy

